// Auto-generated by build_themes.py — do not edit
// 16 themes compiled
const THEMES = {
  "aurora": {
    "name": "极光",
    "description": "紫色渐变系，毛玻璃效果，梦幻极光色彩",
    "series": "classic",
    "tags": [
      "紫色",
      "磨砂",
      "优雅"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "linear-gradient(135deg, rgba(255, 255, 255, 0.9), rgba(248, 250, 252, 0.95))",
      "border_radius": "20px",
      "box_shadow": "0 8px 32px rgba(99, 102, 241, 0.12), 0 2px 8px rgba(168, 85, 247, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.8)",
      "backdrop_filter": "blur(20px)"
    },
    "h1": {
      "style": "padding: 1em 2.2em;\nmargin: 2em 0 1.5em;\nbackground: linear-gradient(135deg, #6366f1 0%, #8b5cf6 30%, #a855f7 60%, #ec4899 100%);\nfont-size: 26px;\nfont-weight: 800;\nline-height: 1.3;\ncolor: #ffffff;\ntext-align: center;\nborder-radius: 16px;\nbox-shadow: 0 8px 24px rgba(168, 85, 247, 0.35), 0 2px 8px rgba(99, 102, 241, 0.25), inset 0 1px 0 rgba(255, 255, 255, 0.3);\nposition: relative;\noverflow: hidden;\nletter-spacing: 0.5px;\ntext-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);\nbackground-clip: padding-box;\n"
    },
    "h2": {
      "style": "margin: 2.5em 0 1.2em;\npadding: 0.8em 1.6em;\nbackground: linear-gradient(135deg, #3b82f6 0%, #6366f1 40%, #8b5cf6 100%);\nfont-size: 22px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #ffffff;\ntext-align: center;\nborder-radius: 14px;\nbox-shadow: 0 4px 16px rgba(139, 92, 246, 0.25), inset 0 1px 0 rgba(255, 255, 255, 0.2);\nletter-spacing: 0.3px;\n"
    },
    "h3": {
      "style": "margin: 2em 0 1em;\npadding: 0.5em 0 0.5em 18px;\nfont-size: 19px;\nfont-weight: 700;\nline-height: 1.4;\ncolor: #6366f1;\nborder-left: 5px solid;\nborder-image: linear-gradient(to bottom, #6366f1, #a855f7, #ec4899) 1;\nborder-bottom: 2px solid transparent;\nborder-image-bottom: linear-gradient(to right, #6366f1, #a855f7, transparent) 1;\nbackground: linear-gradient(to right, rgba(99, 102, 241, 0.08), rgba(168, 85, 247, 0.05), transparent);\nletter-spacing: 0.2px;\n"
    },
    "h4": {
      "style": "margin: 1.8em 0 0.8em;\npadding: 0.4em 0 0.4em 14px;\nfont-size: 17px;\nfont-weight: 700;\nline-height: 1.4;\ncolor: #8b5cf6;\nborder-left: 4px solid #a855f7;\nbackground: linear-gradient(to right, rgba(168, 85, 247, 0.08), rgba(236, 72, 153, 0.04), transparent);\nletter-spacing: 0.2px;\n"
    },
    "h5": {
      "style": "margin: 1.5em 0 0.6em;\npadding: 0.3em 0 0.3em 12px;\nfont-size: 16px;\nfont-weight: 700;\nline-height: 1.4;\ncolor: #6366f1;\nborder-left: 3px solid #6366f1;\nbackground: rgba(99, 102, 241, 0.04);\n"
    },
    "h6": {
      "style": "margin: 1.2em 0 0.5em;\npadding: 0.2em 0 0.2em 10px;\nfont-size: 15px;\nfont-weight: 700;\nline-height: 1.4;\ncolor: #a855f7;\nborder-left: 2px solid #ec4899;\nbackground: rgba(236, 72, 153, 0.04);\n"
    },
    "paragraph": {
      "style": "margin: 1.4em 0;\nletter-spacing: 0.03em;\ncolor: #1e293b;\ntext-align: justify;\nline-height: 1.85;\nfont-size: 15.5px;\ntext-shadow: 0 1px 1px rgba(0, 0, 0, 0.02);\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.8em 0;\ncolor: #1e293b;\nfont-size: 15.5px;\n",
      "item_style": "margin: 0.6em 0;\npadding: 0;\nline-height: 1.8;\nfont-size: 15.5px;\nposition: relative;\npadding-left: 20px;\n",
      "item_style_before": "content: \"•\";\nposition: absolute;\nleft: 0;\ncolor: #a855f7;\nfont-weight: bold;\nfont-size: 1.2em;\nline-height: 1.8;\n",
      "ul_prefix": "",
      "ol_prefix": "{n}."
    },
    "code_block": {
      "style": "font-size: 14px;\noverflow-x: auto;\nborder-radius: 12px;\npadding: 1.4em;\nline-height: 1.6;\nmargin: 1.8em 0;\nbackground: linear-gradient(135deg, rgba(99, 102, 241, 0.03), rgba(168, 85, 247, 0.03), rgba(236, 72, 153, 0.03));\nborder: 2px solid transparent;\nborder-image: linear-gradient(135deg, #6366f1, #a855f7, #ec4899) 1;\nbox-shadow: 0 4px 20px rgba(99, 102, 241, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.5);\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'JetBrains Mono', 'SFMono-Regular', Consolas, Menlo, monospace;\nfont-size: 14px;\nline-height: 1.6;\ncolor: #334155;\n"
    },
    "inline_code": {
      "style": "font-size: 88%;\ncolor: #6366f1;\nbackground: linear-gradient(135deg, rgba(99, 102, 241, 0.1), rgba(168, 85, 247, 0.1));\npadding: 3px 10px;\nborder-radius: 8px;\nfont-family: 'JetBrains Mono', 'SFMono-Regular', Consolas, Menlo, monospace;\nborder: 1px solid rgba(99, 102, 241, 0.2);\nbox-shadow: 0 2px 4px rgba(99, 102, 241, 0.05);\n"
    },
    "blockquote": {
      "style": "font-style: normal;\npadding: 1.2em 1.8em;\nborder-left: 5px solid transparent;\nborder-image: linear-gradient(to bottom, #6366f1, #a855f7, #ec4899) 1;\ncolor: #475569;\nbackground: linear-gradient(135deg, rgba(99, 102, 241, 0.05), rgba(168, 85, 247, 0.05), rgba(236, 72, 153, 0.03));\nborder-radius: 12px;\nmargin: 1.8em 0;\nbox-shadow: 0 2px 12px rgba(168, 85, 247, 0.08);\nborder-right: 1px solid rgba(168, 85, 247, 0.1);\nborder-bottom: 1px solid rgba(168, 85, 247, 0.1);\nborder-top: 1px solid rgba(99, 102, 241, 0.1);\n",
      "p_inner_style": "margin: 0;\nfont-style: normal;\ncolor: #475569;\nline-height: 1.75;\n"
    },
    "link": {
      "style": "color: #6366f1;\ntext-decoration: none;\nborder-bottom: 2px solid transparent;\nborder-image: linear-gradient(to right, rgba(99, 102, 241, 0), #6366f1, #a855f7, #ec4899, rgba(236, 72, 153, 0)) 1;\ntransition: all 0.3s ease;\nposition: relative;\n"
    },
    "image": {
      "container_style": "margin: 2em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 15.5px;\ncolor: #64748b;\n",
      "img_style": "max-width: 100%;\nborder-radius: 16px;\nmargin: 1.5em auto;\ndisplay: block;\nbox-shadow: 0 8px 32px rgba(99, 102, 241, 0.15), 0 2px 8px rgba(0, 0, 0, 0.05);\nborder: 1px solid rgba(168, 85, 247, 0.15);\n"
    },
    "table": {
      "style": "width: 100%;\nborder-collapse: separate;\nborder-spacing: 0;\nmargin: 1.8em 0;\nborder-radius: 12px;\noverflow: hidden;\nbox-shadow: 0 4px 20px rgba(99, 102, 241, 0.1);\nborder: 1px solid rgba(168, 85, 247, 0.15);\n",
      "th_style": "padding: 14px 18px;\ntext-align: left;\nfont-weight: 700;\nborder-bottom: 2px solid rgba(168, 85, 247, 0.2);\nbackground: linear-gradient(135deg, rgba(99, 102, 241, 0.1), rgba(168, 85, 247, 0.1));\ncolor: #6366f1;\nletter-spacing: 0.5px;\n",
      "td_style": "padding: 12px 18px;\nborder-bottom: 1px solid rgba(168, 85, 247, 0.08);\ncolor: #334155;\nbackground: rgba(255, 255, 255, 0.5);\n"
    },
    "hr": {
      "style": "height: 2px;\nborder: none;\nmargin: 3em 0;\nbackground: linear-gradient(90deg, transparent, #6366f1, #8b5cf6, #a855f7, #ec4899, #8b5cf6, #6366f1, transparent);\nborder-radius: 2px;\n"
    },
    "bold": {
      "style": "color: #6366f1;\nfont-weight: 700;\nbackground: linear-gradient(135deg, #6366f1, #a855f7, #ec4899);\n-webkit-background-clip: text;\nbackground-clip: text;\ncolor: transparent;\ntext-shadow: 0 1px 2px rgba(99, 102, 241, 0.1);\n"
    },
    "italic": {
      "style": "color: #a855f7;\nfont-style: italic;\nfont-weight: 500;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #94a3b8;\n"
    },
    "dialogue": {
      "container_style": "margin: 2.5em 0;\npadding: 24px;\nbackground: linear-gradient(135deg, rgba(255, 255, 255, 0.7), rgba(248, 250, 252, 0.8));\nborder-radius: 20px;\nborder: 1px solid rgba(168, 85, 247, 0.2);\nbox-shadow: 0 8px 32px rgba(168, 85, 247, 0.12), 0 2px 8px rgba(99, 102, 241, 0.08), inset 0 1px 0 rgba(255, 255, 255, 0.8);\nbackdrop-filter: blur(10px);\n",
      "title_style": "font-size: 20px;\nfont-weight: 700;\nmargin-bottom: 20px;\ncolor: #6366f1;\ntext-align: center;\nletter-spacing: 0.5px;\nbackground: linear-gradient(135deg, #6366f1, #a855f7, #ec4899);\n-webkit-background-clip: text;\nbackground-clip: text;\ncolor: transparent;\n",
      "message_style": "display: flex;\nmargin-bottom: 18px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background: linear-gradient(135deg, rgba(255, 255, 255, 0.9), rgba(248, 250, 252, 0.95));\ncolor: #1e293b;\npadding: 12px 16px;\nborder-radius: 18px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid rgba(168, 85, 247, 0.15);\nbox-shadow: 0 2px 8px rgba(99, 102, 241, 0.06);\nbackdrop-filter: blur(5px);\n",
      "bubble_right_style": "background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 40%, #a855f7 70%, #ec4899 100%);\ncolor: #ffffff;\npadding: 12px 16px;\nborder-radius: 18px;\nmax-width: 65%;\nword-wrap: break-word;\nbox-shadow: 0 4px 16px rgba(168, 85, 247, 0.3), 0 2px 4px rgba(99, 102, 241, 0.2);\ntext-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);\n",
      "avatar_style": "width: 42px;\nheight: 42px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 700;\nfont-size: 15px;\nflex-shrink: 0;\nmargin: 0 12px;\nbox-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);\n",
      "avatar_left_style": "background: linear-gradient(135deg, #e0e7ff, #ddd6fe);\ncolor: #6366f1;\nborder: 2px solid rgba(99, 102, 241, 0.3);\nbox-shadow: 0 2px 8px rgba(99, 102, 241, 0.15);\n",
      "avatar_right_style": "background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 50%, #a855f7 100%);\ncolor: #ffffff;\nborder: 2px solid rgba(168, 85, 247, 0.5);\nbox-shadow: 0 4px 12px rgba(168, 85, 247, 0.3);\n"
    },
    "body": {
      "background": "linear-gradient(135deg, #f8fafc 0%, #f1f5f9 50%, #e0e7ff 100%)",
      "padding": "20px",
      "margin": "0"
    },
    "decorations": {}
  },
  "blueprint": {
    "name": "蓝图",
    "description": "工程蓝图风格，深蓝底色配白色线条，专业技术感",
    "series": "tech",
    "tags": [
      "蓝图",
      "技术",
      "专业"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "#1b2838",
      "border_radius": "10px",
      "box_shadow": "0 4px 20px rgba(15, 25, 35, 0.4)"
    },
    "h1": {
      "style": "margin: 1.8em 8px 1em;\npadding: 0.8em 0;\nfont-size: 22px;\nfont-weight: 800;\nline-height: 1.3;\ncolor: #ecf0f1;\ntext-align: center;\nborder-bottom: 2px solid #5dade2;\nletter-spacing: 0.08em;\n"
    },
    "h2": {
      "style": "margin: 2em 8px 0.75em;\npadding: 0px 0px 0.5em 14px;\nborder-left: 3px solid #5dade2;\nborder-bottom: 1px dashed rgba(93, 173, 226, 0.3);\nfont-size: 20px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #5dade2;\n"
    },
    "h3": {
      "style": "margin: 1.8em 8px 0.6em;\npadding: 0px 0px 0.4em 12px;\nborder-left: 3px solid #85c1e9;\nfont-size: 18px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #85c1e9;\n"
    },
    "h4": {
      "style": "margin: 1.5em 8px 0.5em;\npadding-left: 12px;\nborder-left: 2px solid #aed6f1;\nfont-size: 16px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #aed6f1;\n"
    },
    "h5": {
      "style": "margin: 1.2em 8px 0.4em;\npadding-left: 10px;\nborder-left: 2px solid #5dade2;\nfont-size: 15px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #aed6f1;\n"
    },
    "h6": {
      "style": "margin: 1em 8px 0.3em;\npadding-left: 8px;\nborder-left: 2px solid rgba(93, 173, 226, 0.5);\nfont-size: 14px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #85c1e9;\n"
    },
    "paragraph": {
      "style": "margin: 1.2em 8px;\ncolor: #d5dbdb;\nfont-family: 'PingFang SC', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif;\nfont-size: 15px;\nline-height: 1.75;\nletter-spacing: 0.06em;\ntext-align: justify;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 8px;\ncolor: #d5dbdb;\nfont-size: 15px;\n",
      "item_style": "margin: 0.5em 0;\npadding: 0;\nline-height: 1.75;\nfont-size: 15px;\ncolor: #d5dbdb;\n",
      "ul_prefix": "- ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 8px;\npadding: 1.2em;\nbackground-color: #0f1923;\nborder-top: 2px solid #5dade2;\nborder-radius: 6px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\nfont-size: 14px;\ncolor: #aed6f1;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "font-size: 90%;\ncolor: #00bcd4;\nbackground-color: rgba(93, 173, 226, 0.12);\npadding: 2px 6px;\nborder-radius: 4px;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 8px;\npadding: 1em 1em 1em 1.5em;\nborder-left: 4px solid #00bcd4;\nborder-radius: 6px;\nbackground-color: #1e3246;\ncolor: #aed6f1;\n",
      "p_inner_style": "margin: 0;\ncolor: #aed6f1;\nline-height: 1.75;\nfont-style: normal;\n"
    },
    "link": {
      "style": "color: #5dade2;\ntext-decoration: none;\nborder-bottom: 1px solid rgba(93, 173, 226, 0.4);\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 14px;\ncolor: #85c1e9;\n",
      "img_style": "max-width: 100%;\ndisplay: block;\nmargin: 0.5em auto;\nborder-radius: 6px;\nbox-shadow: 0 3px 12px rgba(0, 0, 0, 0.3);\nborder: 1px solid rgba(93, 173, 226, 0.2);\n"
    },
    "table": {
      "style": "width: 100%;\nborder-collapse: collapse;\nmargin: 1.5em 0;\nfont-size: 14px;\noverflow: hidden;\n",
      "th_style": "padding: 10px 14px;\ntext-align: left;\nfont-weight: 700;\ncolor: #ecf0f1;\nbackground-color: #0f1923;\nborder: 1px solid #2c4054;\n",
      "td_style": "padding: 8px 14px;\nborder: 1px solid #2c4054;\ncolor: #d5dbdb;\nbackground-color: #1b2838;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 1px;\nmargin: 2em 0;\nbackground: linear-gradient(to right, transparent, #5dade2, #00bcd4, #5dade2, transparent);\nborder-radius: 1px;\n"
    },
    "bold": {
      "style": "font-weight: 700;\ncolor: #ffffff;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #85c1e9;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #566573;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 18px;\nbackground-color: #0f1923;\nborder-radius: 10px;\nborder: 1px solid #2c4054;\n",
      "title_style": "font-size: 17px;\nfont-weight: 700;\nmargin-bottom: 14px;\ncolor: #5dade2;\ntext-align: center;\n",
      "message_style": "display: flex;\nmargin-bottom: 14px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background-color: #1e3246;\ncolor: #d5dbdb;\npadding: 10px 14px;\nborder-radius: 10px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #2c4054;\n",
      "bubble_right_style": "background: linear-gradient(135deg, #1a5276, #2e86c1);\ncolor: #ffffff;\npadding: 10px 14px;\nborder-radius: 10px;\nmax-width: 65%;\nword-wrap: break-word;\nbox-shadow: 0 2px 8px rgba(93, 173, 226, 0.25);\n",
      "avatar_style": "width: 38px;\nheight: 38px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 700;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 10px;\n",
      "avatar_left_style": "background-color: #1e3246;\ncolor: #5dade2;\nborder: 1px solid #2c4054;\n",
      "avatar_right_style": "background: linear-gradient(135deg, #1a5276, #2e86c1);\ncolor: #ffffff;\n"
    },
    "body": {
      "background": "#0f1923",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {}
  },
  "chinese-ink": {
    "name": "水墨丹青",
    "description": "传统中国水墨画风格，宣纸质感配以墨色层次与朱砂点缀，清雅脱俗",
    "series": "oriental",
    "tags": [
      "中国风",
      "水墨",
      "文艺"
    ],
    "container": {
      "max_width": "677px",
      "padding": "8px",
      "background": "#f8f5ef",
      "border_radius": "12px",
      "box_shadow": "0 2px 12px rgba(60, 40, 20, 0.06)"
    },
    "h1": {
      "style": "padding: 1em 2em;\nmargin: 2em 0 1.2em;\nbackground: linear-gradient(135deg, #f5f0e8 0%, #ece4d4 50%, #f5f0e8 100%);\nfont-size: 24px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #8b4513;\ntext-align: center;\nborder-radius: 6px;\nbox-shadow: 0 2px 8px rgba(60, 40, 20, 0.08);\nborder-top: 2px solid rgba(139, 69, 19, 0.3);\nborder-bottom: 2px solid rgba(139, 69, 19, 0.3);\nletter-spacing: 0.15em;\n"
    },
    "h2": {
      "style": "margin: 2em 8px 0.75em 0;\npadding: 0.5em 1em 0.5em 16px;\nborder-left: 4px solid #8b4513;\nfont-size: 20px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #8b4513;\nbackground: linear-gradient(to right, rgba(139, 69, 19, 0.06), rgba(139, 69, 19, 0.02), transparent);\nborder-bottom: 1px solid rgba(139, 69, 19, 0.15);\n"
    },
    "h3": {
      "style": "margin: 2em 8px 0.75em 0;\npadding: 0.4em 0.8em 0.3em 14px;\nborder-left: 4px solid #2e8b57;\nborder-bottom: 1px dashed rgba(46, 139, 87, 0.3);\nfont-size: 18px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #3d5a3a;\n"
    },
    "h4": {
      "style": "margin: 1.5em 8px 0.5em 0;\npadding-left: 12px;\nfont-size: 16px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #5a4030;\nborder-left: 3px solid #8b4513;\n"
    },
    "h5": {
      "style": "margin: 1.2em 8px 0.4em 0;\npadding-left: 10px;\nfont-size: 15px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #6b5040;\nborder-left: 2px solid #8b4513;\n"
    },
    "h6": {
      "style": "margin: 1em 8px 0.3em 0;\npadding-left: 8px;\nfont-size: 14px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #7a6050;\nborder-left: 1px solid #2e8b57;\n"
    },
    "paragraph": {
      "style": "margin: 1.2em 8px;\ntext-align: justify;\nline-height: 1.85;\nfont-family: 'PingFang SC', 'STSong', 'Songti SC', 'KaiTi', serif;\nfont-size: 15px;\nletter-spacing: 0.06em;\ncolor: #2c2420;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 8px;\ncolor: #2c2420;\nfont-size: 15px;\n",
      "item_style": "margin: 0.5em 0;\npadding: 0;\nline-height: 1.8;\nfont-size: 15px;\ncolor: #2c2420;\n",
      "ul_prefix": "○ ",
      "ol_prefix": "{n}、"
    },
    "code_block": {
      "style": "margin: 1.5em 8px;\npadding: 1.2em;\nbackground-color: #f5f1ea;\nborder-radius: 4px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\nborder: 1px solid #e5dcd0;\nborder-top: 3px solid #8b4513;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'Courier New', Menlo, monospace;\nfont-size: 14px;\ncolor: #3a3028;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "background-color: rgba(139, 69, 19, 0.08);\ncolor: #8b4513;\nfont-family: 'Courier New', Menlo, monospace;\npadding: 2px 6px;\nborder-radius: 3px;\nfont-size: 90%;\nborder: 1px solid rgba(139, 69, 19, 0.12);\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 0 2em;\npadding: 1em 1.5em;\nborder-left: 4px solid #2e8b57;\nbackground: #f5f2eb;\ncolor: #4a4035;\nborder-radius: 4px;\nbox-shadow: 0 1px 4px rgba(60, 40, 20, 0.05);\n",
      "p_inner_style": "margin: 0;\ncolor: #4a4035;\nline-height: 1.8;\nfont-style: normal;\nfont-size: 15px;\n"
    },
    "link": {
      "style": "color: #8b4513;\ntext-decoration: none;\nborder-bottom: 1px dashed rgba(139, 69, 19, 0.4);\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\n",
      "img_style": "max-width: 100%;\nmargin: 1em auto;\ndisplay: block;\nborder-radius: 4px;\nbox-shadow: 0 2px 8px rgba(60, 40, 20, 0.1);\nborder: 1px solid #e5dcd0;\n"
    },
    "table": {
      "style": "margin: 1.5em 0;\nwidth: 100%;\nborder-collapse: collapse;\nfont-size: 15px;\n",
      "th_style": "background: #8b4513;\ncolor: #ffffff;\npadding: 10px 14px;\ntext-align: left;\nfont-weight: 600;\n",
      "td_style": "border: 1px solid #e5dcd0;\npadding: 10px 14px;\ncolor: #2c2420;\nbackground: #faf7f2;\n"
    },
    "hr": {
      "style": ""
    },
    "bold": {
      "style": "font-weight: bold;\ncolor: #8b4513;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #2e8b57;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #999999;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 20px;\nbackground: linear-gradient(to bottom, #f8f5ef, #f3efe6);\nborder-radius: 8px;\nborder: 1px solid #e5dcd0;\nbox-shadow: 0 2px 8px rgba(60, 40, 20, 0.05);\n",
      "title_style": "font-size: 18px;\nfont-weight: 600;\nmargin-bottom: 16px;\ncolor: #8b4513;\ntext-align: center;\nletter-spacing: 0.1em;\n",
      "message_style": "display: flex;\nmargin-bottom: 16px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background: #faf7f2;\ncolor: #4a4035;\npadding: 12px 16px;\nborder-radius: 12px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #e5dcd0;\n",
      "bubble_right_style": "background: linear-gradient(135deg, #8b4513, #a0522d);\ncolor: #ffffff;\npadding: 12px 16px;\nborder-radius: 12px;\nmax-width: 65%;\nword-wrap: break-word;\nbox-shadow: 0 2px 6px rgba(139, 69, 19, 0.2);\n",
      "avatar_style": "width: 40px;\nheight: 40px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 600;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 12px;\n",
      "avatar_left_style": "background: #e5dcd0;\ncolor: #2e8b57;\nborder: 2px solid #d5cab8;\n",
      "avatar_right_style": "background: linear-gradient(135deg, #8b4513, #a0522d);\ncolor: #ffffff;\n"
    },
    "body": {
      "background": "#f0ece4",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {
      "h2_prefix": "◈ ",
      "ul_prefix": "○ ",
      "hr_text": "— ✦ —"
    }
  },
  "default": {
    "name": "墨印默认",
    "description": "蓝灰色系，清爽专业，适合各类内容",
    "series": "classic",
    "tags": [
      "默认",
      "蓝灰",
      "通用"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "#ffffff",
      "border_radius": "12px",
      "box_shadow": "0 2px 12px rgba(44, 62, 80, 0.08)"
    },
    "h1": {
      "style": "margin: 1.8em 8px 1em;\npadding: 0.9em 1.6em;\nfont-size: 22px;\nfont-weight: 800;\nline-height: 1.3;\ncolor: #ffffff;\ntext-align: center;\nbackground: #2c3e50;\nborder-radius: 8px;\nbox-shadow: 0 3px 10px rgba(44, 62, 80, 0.2);\nletter-spacing: 0.05em;\n"
    },
    "h2": {
      "style": "margin: 2em 8px 0.75em;\npadding: 0px 0px 0.5em 14px;\nborder-left: 4px solid #3498db;\nborder-bottom: 1px dashed #3498db;\nfont-size: 20px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #2c3e50;\n"
    },
    "h3": {
      "style": "margin: 1.8em 8px 0.6em;\npadding: 0px 0px 0.4em 12px;\nborder-left: 4px solid #3498db;\nborder-bottom: 1px dashed rgba(52, 152, 219, 0.4);\nfont-size: 18px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #2c3e50;\n"
    },
    "h4": {
      "style": "margin: 1.5em 8px 0.5em;\npadding-left: 12px;\nborder-left: 3px solid #5dade2;\nfont-size: 16px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #34495e;\n"
    },
    "h5": {
      "style": "margin: 1.2em 8px 0.4em;\npadding-left: 10px;\nborder-left: 3px solid #85c1e9;\nfont-size: 15px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #34495e;\n"
    },
    "h6": {
      "style": "margin: 1em 8px 0.3em;\npadding-left: 8px;\nborder-left: 2px solid #aed6f1;\nfont-size: 14px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #5d6d7e;\n"
    },
    "paragraph": {
      "style": "margin: 1.2em 8px;\ncolor: #2c3e50;\nfont-family: 'PingFang SC', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif;\nfont-size: 15px;\nline-height: 1.75;\nletter-spacing: 0.1em;\ntext-align: justify;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 8px;\ncolor: #2c3e50;\nfont-size: 15px;\n",
      "item_style": "margin: 0.5em 0;\npadding: 0;\nline-height: 1.75;\nfont-size: 15px;\ncolor: #2c3e50;\n",
      "ul_prefix": "• ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 8px;\npadding: 1.2em;\nbackground-color: #f8f9fa;\nborder-top: 3px solid #3498db;\nborder-radius: 6px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\nfont-size: 14px;\ncolor: #2c3e50;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "font-size: 90%;\ncolor: #3498db;\nbackground-color: rgba(52, 152, 219, 0.1);\npadding: 2px 6px;\nborder-radius: 4px;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 8px;\npadding: 1em 1em 1em 1.5em;\nborder-left: 4px solid #3498db;\nborder-radius: 4px;\nbackground-color: #f0f4f8;\ncolor: #5d6d7e;\nfont-style: italic;\n",
      "p_inner_style": "margin: 0;\ncolor: #5d6d7e;\nline-height: 1.75;\nfont-style: italic;\n"
    },
    "link": {
      "style": "color: #3498db;\ntext-decoration: none;\nborder-bottom: 1px solid rgba(52, 152, 219, 0.3);\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 14px;\ncolor: #7f8c8d;\n",
      "img_style": "max-width: 100%;\ndisplay: block;\nmargin: 0.5em auto;\nborder-radius: 6px;\nbox-shadow: 0 2px 8px rgba(44, 62, 80, 0.1);\n"
    },
    "table": {
      "style": "width: 100%;\nborder-collapse: collapse;\nmargin: 1.5em 0;\nfont-size: 14px;\nborder-radius: 6px;\noverflow: hidden;\n",
      "th_style": "padding: 10px 14px;\ntext-align: left;\nfont-weight: 700;\ncolor: #ffffff;\nbackground-color: #3498db;\nborder: 1px solid #2e86c1;\n",
      "td_style": "padding: 8px 14px;\nborder: 1px solid #d5dbdb;\ncolor: #2c3e50;\nbackground-color: #ffffff;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 2px;\nmargin: 2em 0;\nbackground: linear-gradient(to right, transparent, #3498db, #2c3e50, #3498db, transparent);\nborder-radius: 2px;\n"
    },
    "bold": {
      "style": "font-weight: 700;\ncolor: #2980b9;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #5d6d7e;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #95a5a6;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 18px;\nbackground-color: #f0f4f8;\nborder-radius: 10px;\nborder: 1px solid #d5dbdb;\n",
      "title_style": "font-size: 17px;\nfont-weight: 700;\nmargin-bottom: 14px;\ncolor: #2c3e50;\ntext-align: center;\n",
      "message_style": "display: flex;\nmargin-bottom: 14px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background-color: #ffffff;\ncolor: #2c3e50;\npadding: 10px 14px;\nborder-radius: 10px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #d5dbdb;\n",
      "bubble_right_style": "background-color: #3498db;\ncolor: #ffffff;\npadding: 10px 14px;\nborder-radius: 10px;\nmax-width: 65%;\nword-wrap: break-word;\nbox-shadow: 0 2px 6px rgba(52, 152, 219, 0.25);\n",
      "avatar_style": "width: 38px;\nheight: 38px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 700;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 10px;\n",
      "avatar_left_style": "background-color: #d5dbdb;\ncolor: #2c3e50;\n",
      "avatar_right_style": "background-color: #3498db;\ncolor: #ffffff;\n"
    },
    "body": {
      "background": "#eef2f7",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {}
  },
  "elegant-serif": {
    "name": "典雅衬线",
    "description": "优雅衬线字体搭配暖棕色调，适合深度阅读和文学内容",
    "series": "classic",
    "tags": [
      "典雅",
      "衬线",
      "阅读"
    ],
    "container": {
      "max_width": "677px",
      "padding": "20px",
      "background": "#fefdfb",
      "border_radius": "8px",
      "box_shadow": "0 2px 12px rgba(139, 115, 85, 0.06)"
    },
    "h1": {
      "style": "padding: 0.6em 0;\nmargin: 1.8em 0 1em;\nfont-size: 26px;\nfont-weight: 700;\ntext-align: center;\nline-height: 1.4;\ncolor: #1a1a1a;\nfont-family: Georgia, 'Times New Roman', serif;\nletter-spacing: 0.05em;\n"
    },
    "h2": {
      "style": "margin: 2em 0 0.8em;\npadding: 0.3em 0 0.3em 14px;\nfont-size: 20px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #1a1a1a;\nfont-family: Georgia, 'Times New Roman', serif;\nborder-left: 4px solid #8b7355;\n"
    },
    "h3": {
      "style": "margin: 1.8em 0 0.6em;\npadding: 0.2em 0 0.2em 12px;\nfont-size: 18px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #2c2c2c;\nfont-family: Georgia, 'Times New Roman', serif;\nborder-left: 3px solid #a08c6e;\n"
    },
    "h4": {
      "style": "margin: 1.5em 0 0.5em;\npadding: 0.2em 0 0.2em 10px;\nfont-size: 16px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #2c2c2c;\nfont-family: Georgia, 'Times New Roman', serif;\nborder-left: 3px solid #b8a88a;\n"
    },
    "h5": {
      "style": "margin: 1.2em 0 0.4em;\npadding: 0 0 0 8px;\nfont-size: 15px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #3c3c3c;\nfont-family: Georgia, 'Times New Roman', serif;\nborder-left: 2px solid #c4b49a;\n"
    },
    "h6": {
      "style": "margin: 1em 0 0.3em;\npadding: 0 0 0 8px;\nfont-size: 14px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #555555;\nfont-family: Georgia, 'Times New Roman', serif;\nborder-left: 2px solid #d4c8b0;\n"
    },
    "paragraph": {
      "style": "margin: 1.4em 0;\ncolor: #2c2c2c;\nfont-family: Georgia, 'Times New Roman', serif;\nfont-size: 16px;\nline-height: 1.85;\ntext-align: justify;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 0;\ncolor: #2c2c2c;\nfont-family: Georgia, 'Times New Roman', serif;\nfont-size: 16px;\n",
      "item_style": "margin: 0.5em 0;\npadding: 0;\nline-height: 1.8;\nfont-size: 16px;\n",
      "ul_prefix": "- ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 0;\npadding: 1.2em;\nbackground-color: #f5f3ef;\nborder-radius: 6px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\nborder: 1px solid #e8e2d8;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\nfont-size: 14px;\ncolor: #2c2c2c;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "font-size: 90%;\ncolor: #8b7355;\nbackground-color: #f5f3ef;\npadding: 2px 6px;\nborder-radius: 3px;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\nborder: 1px solid #e8e2d8;\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 0;\npadding: 1em 1.5em;\nborder-left: 4px solid #8b7355;\nbackground-color: rgba(139, 115, 85, 0.04);\nborder-radius: 4px;\n",
      "p_inner_style": "margin: 0;\ncolor: #555555;\nline-height: 1.8;\nfont-style: italic;\nfont-family: Georgia, 'Times New Roman', serif;\n"
    },
    "link": {
      "style": "color: #8b7355;\ntext-decoration: none;\nborder-bottom: 1px solid rgba(139, 115, 85, 0.4);\n"
    },
    "image": {
      "container_style": "margin: 2em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 13px;\ncolor: #999999;\nfont-family: Georgia, 'Times New Roman', serif;\nfont-style: italic;\n",
      "img_style": "max-width: 100%;\ndisplay: block;\nmargin: 1.5em auto;\nborder-radius: 4px;\nbox-shadow: 0 2px 10px rgba(139, 115, 85, 0.1);\n"
    },
    "table": {
      "style": "width: 100%;\nborder-collapse: collapse;\nmargin: 1.5em 0;\nfont-family: Georgia, 'Times New Roman', serif;\nfont-size: 15px;\n",
      "th_style": "padding: 12px 15px;\ntext-align: left;\nfont-weight: 700;\ncolor: #1a1a1a;\nborder-bottom: 2px solid #8b7355;\nbackground-color: rgba(139, 115, 85, 0.06);\n",
      "td_style": "padding: 10px 15px;\nborder-bottom: 1px solid #e8e2d8;\ncolor: #2c2c2c;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 1px;\nmargin: 2.5em 0;\nbackground: linear-gradient(to right, transparent, #8b7355, transparent);\n"
    },
    "bold": {
      "style": "font-weight: 700;\ncolor: #5c4a32;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #8b7355;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #bbbbbb;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 20px;\nbackground-color: #faf8f5;\nborder-radius: 8px;\nborder: 1px solid #e8e2d8;\n",
      "title_style": "font-size: 18px;\nfont-weight: 700;\nmargin-bottom: 16px;\ncolor: #8b7355;\ntext-align: center;\nfont-family: Georgia, 'Times New Roman', serif;\n",
      "message_style": "display: flex;\nmargin-bottom: 16px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background-color: #ffffff;\ncolor: #2c2c2c;\npadding: 10px 14px;\nborder-radius: 12px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #e8e2d8;\nfont-family: Georgia, 'Times New Roman', serif;\n",
      "bubble_right_style": "background-color: #8b7355;\ncolor: #ffffff;\npadding: 10px 14px;\nborder-radius: 12px;\nmax-width: 65%;\nword-wrap: break-word;\nbox-shadow: 0 2px 8px rgba(139, 115, 85, 0.2);\n",
      "avatar_style": "width: 40px;\nheight: 40px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 600;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 12px;\n",
      "avatar_left_style": "background-color: #f0ebe4;\ncolor: #8b7355;\nborder: 1px solid #e8e2d8;\n",
      "avatar_right_style": "background-color: #8b7355;\ncolor: #ffffff;\n"
    },
    "decorations": {
      "h2_prefix": "§ ",
      "blockquote_prefix": "",
      "blockquote_suffix": "",
      "hr_text": ""
    },
    "body": {
      "background": "#f9f7f3",
      "padding": "16px",
      "margin": "0"
    }
  },
  "github-dark": {
    "name": "GitHub Dark",
    "description": "GitHub 暗色模式风格，开发者熟悉的深色界面",
    "series": "tech",
    "tags": [
      "GitHub",
      "暗色",
      "开发者"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "#0d1117",
      "border_radius": "12px",
      "box_shadow": "0 2px 12px rgba(0, 0, 0, 0.3)"
    },
    "h1": {
      "style": "margin: 1.5em 8px 0.75em 0px;\npadding: 0px 0px 0.4em 0px;\nfont-size: 22px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #e6edf3;\nborder-bottom: 1px solid #30363d;\n"
    },
    "h2": {
      "style": "margin: 2em 8px 0.75em 0px;\npadding: 0px 0px 0.35em 0px;\nfont-size: 20px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #e6edf3;\nborder-bottom: 1px solid #30363d;\n"
    },
    "h3": {
      "style": "margin: 2em 8px 0.75em 0px;\npadding: 0px;\nfont-size: 18px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #e6edf3;\n"
    },
    "h4": {
      "style": "margin: 1.5em 8px 0.5em 0px;\npadding: 0px;\nfont-size: 16px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #e6edf3;\n"
    },
    "h5": {
      "style": "margin: 1.2em 8px 0.4em 0px;\npadding: 0px;\nfont-size: 15px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #e6edf3;\n"
    },
    "h6": {
      "style": "margin: 1em 8px 0.3em 0px;\npadding: 0px;\nfont-size: 14px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #848d97;\n"
    },
    "paragraph": {
      "style": "margin: 1em 8px;\ntext-align: left;\nline-height: 1.6;\nfont-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;\nfont-size: 16px;\ncolor: #e6edf3;\noverflow-wrap: break-word;\n"
    },
    "list": {
      "container_style": "list-style: none;\nmargin: 0em 8px 1em;\npadding: 0px;\ntext-align: left;\nline-height: 1.6;\nfont-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;\nfont-size: 16px;\ncolor: #e6edf3;\n",
      "item_style": "margin: 0.25em 0px;\npadding: 0px;\ntext-align: left;\nline-height: 1.6;\nfont-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;\nfont-size: 16px;\ncolor: #e6edf3;\n",
      "ul_prefix": "• ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 8px;\npadding: 16px;\nbackground-color: #161b22;\nborder-radius: 6px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.45;\nborder: 1px solid #30363d;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;\nfont-size: 14px;\ncolor: #e6edf3;\nline-height: 1.45;\n"
    },
    "inline_code": {
      "style": "background-color: rgba(31, 111, 235, 0.25);\ncolor: #e6edf3;\nfont-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;\npadding: 3px 6px;\nborder-radius: 6px;\nfont-size: 85%;\n"
    },
    "blockquote": {
      "style": "margin: 1em 0;\npadding: 0.5em 1em;\nborder-left: 4px solid #30363d;\nborder-radius: 0px;\nbackground: #161b22;\ncolor: #848d97;\nfont-style: normal;\n",
      "p_inner_style": "margin: 0px;\ntext-align: left;\nline-height: 1.6;\nfont-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Noto Sans', Helvetica, Arial, sans-serif;\nfont-size: 16px;\ndisplay: block;\ncolor: #848d97;\nfont-style: normal;\n"
    },
    "link": {
      "style": "color: #58a6ff;\ntext-decoration: none;\nborder-bottom: 1px solid transparent;\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 14px;\ncolor: #848d97;\n",
      "img_style": "display: block;\nmax-width: 100%;\nmargin: 0.1em auto 0.5em;\nborder-radius: 6px;\nbox-shadow: 0 2px 8px rgba(0, 0, 0, 0.3);\nborder: 1px solid #30363d;\n"
    },
    "table": {
      "style": "margin: 1.5em 0;\nwidth: 100%;\nborder-collapse: collapse;\nfont-size: 14px;\ncolor: #e6edf3;\n",
      "th_style": "background: #161b22;\ncolor: #e6edf3;\npadding: 10px 13px;\ntext-align: left;\nfont-weight: 600;\nborder: 1px solid #30363d;\n",
      "td_style": "border: 1px solid #30363d;\npadding: 10px 13px;\ncolor: #e6edf3;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 4px;\nmargin: 1.5em 0;\npadding: 0;\nbackground: #30363d;\nborder-radius: 2px;\n"
    },
    "bold": {
      "style": "font-weight: 600;\ncolor: #ffffff;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #e6edf3;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #848d97;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 20px;\nbackground: #161b22;\nborder-radius: 6px;\nborder: 1px solid #30363d;\n",
      "title_style": "font-size: 18px;\nfont-weight: 600;\nmargin-bottom: 16px;\ncolor: #e6edf3;\ntext-align: center;\n",
      "message_style": "display: flex;\nmargin-bottom: 16px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background: #21262d;\ncolor: #e6edf3;\npadding: 10px 14px;\nborder-radius: 12px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #30363d;\n",
      "bubble_right_style": "background: #1f6feb;\ncolor: #ffffff;\npadding: 10px 14px;\nborder-radius: 12px;\nmax-width: 65%;\nword-wrap: break-word;\n",
      "avatar_style": "width: 40px;\nheight: 40px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 600;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 12px;\n",
      "avatar_left_style": "background: #21262d;\ncolor: #e6edf3;\nborder: 1px solid #30363d;\n",
      "avatar_right_style": "background: #1f6feb;\ncolor: #ffffff;\n"
    },
    "body": {
      "background": "#010409",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {}
  },
  "minimal": {
    "name": "极简",
    "description": "超级极简风格，无阴影无装饰，纯净阅读体验",
    "series": "classic",
    "tags": [
      "极简",
      "干净",
      "通用"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "#ffffff",
      "border_radius": "0px",
      "box_shadow": ""
    },
    "h1": {
      "style": "margin: 1.8em 0 0.8em;\npadding: 0;\nfont-size: 24px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #000000;\n"
    },
    "h2": {
      "style": "margin: 2em 0 0.7em;\npadding: 0;\nfont-size: 20px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #000000;\n"
    },
    "h3": {
      "style": "margin: 1.8em 0 0.6em;\npadding: 0;\nfont-size: 18px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #1a1a1a;\n"
    },
    "h4": {
      "style": "margin: 1.5em 0 0.5em;\npadding: 0;\nfont-size: 16px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #1a1a1a;\n"
    },
    "h5": {
      "style": "margin: 1.2em 0 0.4em;\npadding: 0;\nfont-size: 15px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #333333;\n"
    },
    "h6": {
      "style": "margin: 1em 0 0.3em;\npadding: 0;\nfont-size: 14px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #666666;\n"
    },
    "paragraph": {
      "style": "margin: 1.2em 0;\ncolor: #333333;\nfont-size: 15px;\nline-height: 1.75;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 0;\ncolor: #333333;\nfont-size: 15px;\n",
      "item_style": "margin: 0.4em 0;\npadding: 0;\nline-height: 1.75;\nfont-size: 15px;\n",
      "ul_prefix": "- ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 0;\npadding: 1em;\nbackground-color: #f6f8fa;\nborder-radius: 6px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\nborder: 1px solid #e1e4e8;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;\nfont-size: 14px;\ncolor: #24292e;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "font-size: 90%;\ncolor: #24292e;\nbackground-color: #f6f8fa;\npadding: 2px 6px;\nborder-radius: 3px;\nfont-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;\nborder: 1px solid #e1e4e8;\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 0;\npadding: 0.5em 1em;\nborder-left: 3px solid #dddddd;\ncolor: #666666;\n",
      "p_inner_style": "margin: 0;\ncolor: #666666;\nline-height: 1.75;\nfont-style: normal;\n"
    },
    "link": {
      "style": "color: #0366d6;\ntext-decoration: none;\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\n",
      "img_style": "max-width: 100%;\ndisplay: block;\nmargin: 1em auto;\n"
    },
    "table": {
      "style": "width: 100%;\nborder-collapse: collapse;\nmargin: 1.5em 0;\nfont-size: 15px;\n",
      "th_style": "padding: 10px 12px;\ntext-align: left;\nfont-weight: 600;\ncolor: #24292e;\nborder-bottom: 2px solid #e1e4e8;\n",
      "td_style": "padding: 8px 12px;\nborder-bottom: 1px solid #e1e4e8;\ncolor: #333333;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 1px;\nmargin: 2em 0;\nbackground-color: #e1e4e8;\n"
    },
    "bold": {
      "style": "font-weight: 700;\ncolor: #000000;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #666666;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #999999;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 16px;\nbackground-color: #f6f8fa;\nborder-radius: 6px;\nborder: 1px solid #e1e4e8;\n",
      "title_style": "font-size: 16px;\nfont-weight: 600;\nmargin-bottom: 12px;\ncolor: #24292e;\ntext-align: center;\n",
      "message_style": "display: flex;\nmargin-bottom: 12px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background-color: #ffffff;\ncolor: #333333;\npadding: 8px 12px;\nborder-radius: 8px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #e1e4e8;\n",
      "bubble_right_style": "background-color: #0366d6;\ncolor: #ffffff;\npadding: 8px 12px;\nborder-radius: 8px;\nmax-width: 65%;\nword-wrap: break-word;\n",
      "avatar_style": "width: 36px;\nheight: 36px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 600;\nfont-size: 13px;\nflex-shrink: 0;\nmargin: 0 10px;\n",
      "avatar_left_style": "background-color: #e1e4e8;\ncolor: #24292e;\n",
      "avatar_right_style": "background-color: #0366d6;\ncolor: #ffffff;\n"
    },
    "decorations": {
      "h2_prefix": "",
      "blockquote_prefix": "",
      "blockquote_suffix": "",
      "hr_text": ""
    },
    "body": {
      "background": "#ffffff",
      "padding": "16px",
      "margin": "0"
    }
  },
  "mint": {
    "name": "薄荷清新",
    "description": "清新薄荷绿色系，轻松活泼，适合生活和健康内容",
    "series": "social",
    "tags": [
      "薄荷",
      "绿色",
      "清新"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "#f0faf7",
      "border_radius": "14px",
      "box_shadow": "0 4px 18px rgba(26, 188, 156, 0.08)"
    },
    "h1": {
      "style": "margin: 1.8em 8px 1em;\npadding: 1em 1.8em;\nfont-size: 22px;\nfont-weight: 800;\nline-height: 1.3;\ncolor: #ffffff;\ntext-align: center;\nbackground: #1abc9c;\nborder-radius: 10px;\nbox-shadow: 0 4px 14px rgba(26, 188, 156, 0.3);\nletter-spacing: 0.06em;\n"
    },
    "h2": {
      "style": "margin: 2em 8px 0.75em;\npadding: 0px 0px 0.5em 14px;\nborder-left: 4px solid #16a085;\nborder-bottom: 1px dashed rgba(22, 160, 133, 0.35);\nfont-size: 20px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #0e6655;\n"
    },
    "h3": {
      "style": "margin: 1.8em 8px 0.6em;\npadding: 0px 0px 0.4em 12px;\nborder-left: 4px solid #1abc9c;\nfont-size: 18px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #117a65;\n"
    },
    "h4": {
      "style": "margin: 1.5em 8px 0.5em;\npadding-left: 12px;\nborder-left: 3px solid #2ecc71;\nfont-size: 16px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #148f77;\n"
    },
    "h5": {
      "style": "margin: 1.2em 8px 0.4em;\npadding-left: 10px;\nborder-left: 3px solid #76d7c4;\nfont-size: 15px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #17a589;\n"
    },
    "h6": {
      "style": "margin: 1em 8px 0.3em;\npadding-left: 8px;\nborder-left: 2px solid #a9dfbf;\nfont-size: 14px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #1e8449;\n"
    },
    "paragraph": {
      "style": "margin: 1.2em 8px;\ncolor: #333333;\nfont-family: 'PingFang SC', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif;\nfont-size: 15px;\nline-height: 1.75;\nletter-spacing: 0.06em;\ntext-align: justify;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 8px;\ncolor: #333333;\nfont-size: 15px;\n",
      "item_style": "margin: 0.5em 0;\npadding: 0;\nline-height: 1.75;\nfont-size: 15px;\ncolor: #333333;\n",
      "ul_prefix": "✦ ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 8px;\npadding: 1.2em;\nbackground-color: #e8f8f5;\nborder-top: 3px solid #1abc9c;\nborder-radius: 8px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\nfont-size: 14px;\ncolor: #0e6655;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "font-size: 90%;\ncolor: #16a085;\nbackground-color: rgba(26, 188, 156, 0.1);\npadding: 2px 6px;\nborder-radius: 4px;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 8px;\npadding: 1em 1em 1em 1.5em;\nborder-left: 4px solid #2ecc71;\nborder-radius: 6px;\nbackground-color: #d5f5e3;\ncolor: #1e8449;\n",
      "p_inner_style": "margin: 0;\ncolor: #1e8449;\nline-height: 1.75;\nfont-style: normal;\n"
    },
    "link": {
      "style": "color: #1abc9c;\ntext-decoration: none;\nborder-bottom: 1px solid rgba(26, 188, 156, 0.4);\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 14px;\ncolor: #1e8449;\n",
      "img_style": "max-width: 100%;\ndisplay: block;\nmargin: 0.5em auto;\nborder-radius: 8px;\nbox-shadow: 0 3px 12px rgba(26, 188, 156, 0.12);\n"
    },
    "table": {
      "style": "width: 100%;\nborder-collapse: collapse;\nmargin: 1.5em 0;\nfont-size: 14px;\noverflow: hidden;\n",
      "th_style": "padding: 10px 14px;\ntext-align: left;\nfont-weight: 700;\ncolor: #ffffff;\nbackground-color: #1abc9c;\nborder: 1px solid #16a085;\n",
      "td_style": "padding: 8px 14px;\nborder: 1px solid #a9dfbf;\ncolor: #333333;\nbackground-color: #ffffff;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 2px;\nmargin: 2em 0;\nbackground: linear-gradient(to right, transparent, #1abc9c, #2ecc71, #1abc9c, transparent);\nborder-radius: 2px;\n"
    },
    "bold": {
      "style": "font-weight: 700;\ncolor: #16a085;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #1e8449;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #aab7b8;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 18px;\nbackground-color: #d5f5e3;\nborder-radius: 12px;\nborder: 1px solid #a9dfbf;\n",
      "title_style": "font-size: 17px;\nfont-weight: 700;\nmargin-bottom: 14px;\ncolor: #0e6655;\ntext-align: center;\n",
      "message_style": "display: flex;\nmargin-bottom: 14px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background-color: #ffffff;\ncolor: #333333;\npadding: 10px 14px;\nborder-radius: 10px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #a9dfbf;\n",
      "bubble_right_style": "background: linear-gradient(135deg, #1abc9c, #16a085);\ncolor: #ffffff;\npadding: 10px 14px;\nborder-radius: 10px;\nmax-width: 65%;\nword-wrap: break-word;\nbox-shadow: 0 2px 8px rgba(26, 188, 156, 0.3);\n",
      "avatar_style": "width: 38px;\nheight: 38px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 700;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 10px;\n",
      "avatar_left_style": "background-color: #d5f5e3;\ncolor: #16a085;\nborder: 1px solid #a9dfbf;\n",
      "avatar_right_style": "background: linear-gradient(135deg, #1abc9c, #16a085);\ncolor: #ffffff;\n"
    },
    "body": {
      "background": "#d0ece7",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {
      "ul_prefix": "✦ "
    }
  },
  "ocean": {
    "name": "深海",
    "description": "深海蓝色系，宁静深邃，适合科技和商务内容",
    "series": "classic",
    "tags": [
      "海洋",
      "蓝色",
      "清新"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "#f4f8fb",
      "border_radius": "14px",
      "box_shadow": "0 4px 18px rgba(12, 35, 64, 0.08)"
    },
    "h1": {
      "style": "margin: 1.8em 8px 1em;\npadding: 1em 1.8em;\nfont-size: 22px;\nfont-weight: 800;\nline-height: 1.3;\ncolor: #ffffff;\ntext-align: center;\nbackground: linear-gradient(135deg, #0c2340, #1a5276);\nborder-radius: 10px;\nbox-shadow: 0 4px 16px rgba(12, 35, 64, 0.3);\nletter-spacing: 0.06em;\n"
    },
    "h2": {
      "style": "margin: 2em 8px 0.75em;\npadding: 0px 0px 0.5em 14px;\nborder-left: 4px solid #2e86c1;\nborder-bottom: 1px dashed rgba(46, 134, 193, 0.35);\nfont-size: 20px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #0c2340;\n"
    },
    "h3": {
      "style": "margin: 1.8em 8px 0.6em;\npadding: 0px 0px 0.4em 12px;\nborder-left: 4px solid #2e86c1;\nfont-size: 18px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #1a5276;\n"
    },
    "h4": {
      "style": "margin: 1.5em 8px 0.5em;\npadding-left: 12px;\nborder-left: 3px solid #5dade2;\nfont-size: 16px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #1a5276;\n"
    },
    "h5": {
      "style": "margin: 1.2em 8px 0.4em;\npadding-left: 10px;\nborder-left: 3px solid #85c1e9;\nfont-size: 15px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #21618c;\n"
    },
    "h6": {
      "style": "margin: 1em 8px 0.3em;\npadding-left: 8px;\nborder-left: 2px solid #aed6f1;\nfont-size: 14px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #2e86c1;\n"
    },
    "paragraph": {
      "style": "margin: 1.2em 8px;\ncolor: #1c2833;\nfont-family: 'PingFang SC', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif;\nfont-size: 15px;\nline-height: 1.75;\nletter-spacing: 0.06em;\ntext-align: justify;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 8px;\ncolor: #1c2833;\nfont-size: 15px;\n",
      "item_style": "margin: 0.5em 0;\npadding: 0;\nline-height: 1.75;\nfont-size: 15px;\ncolor: #1c2833;\n",
      "ul_prefix": "◆ ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 8px;\npadding: 1.2em;\nbackground-color: #eaf2f8;\nborder-top: 3px solid #2e86c1;\nborder-radius: 8px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\nfont-size: 14px;\ncolor: #0c2340;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "font-size: 90%;\ncolor: #1a5276;\nbackground-color: rgba(46, 134, 193, 0.1);\npadding: 2px 6px;\nborder-radius: 4px;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 8px;\npadding: 1em 1em 1em 1.5em;\nborder-left: 4px solid #2e86c1;\nborder-radius: 6px;\nbackground-color: #d6eaf8;\ncolor: #1c2833;\n",
      "p_inner_style": "margin: 0;\ncolor: #1c2833;\nline-height: 1.75;\nfont-style: normal;\n"
    },
    "link": {
      "style": "color: #2e86c1;\ntext-decoration: none;\nborder-bottom: 1px solid rgba(46, 134, 193, 0.4);\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 14px;\ncolor: #5d6d7e;\n",
      "img_style": "max-width: 100%;\ndisplay: block;\nmargin: 0.5em auto;\nborder-radius: 8px;\nbox-shadow: 0 3px 12px rgba(12, 35, 64, 0.12);\n"
    },
    "table": {
      "style": "width: 100%;\nborder-collapse: collapse;\nmargin: 1.5em 0;\nfont-size: 14px;\noverflow: hidden;\n",
      "th_style": "padding: 10px 14px;\ntext-align: left;\nfont-weight: 700;\ncolor: #ffffff;\nbackground: linear-gradient(135deg, #0c2340, #1a5276);\nborder: 1px solid #154360;\n",
      "td_style": "padding: 8px 14px;\nborder: 1px solid #d6eaf8;\ncolor: #1c2833;\nbackground-color: #ffffff;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 2px;\nmargin: 2em 0;\nbackground: linear-gradient(to right, #0c2340, #2e86c1, #85c1e9, #2e86c1, #0c2340);\nborder-radius: 2px;\n"
    },
    "bold": {
      "style": "font-weight: 700;\ncolor: #0c2340;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #5d6d7e;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #85929e;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 18px;\nbackground-color: #d6eaf8;\nborder-radius: 12px;\nborder: 1px solid #aed6f1;\n",
      "title_style": "font-size: 17px;\nfont-weight: 700;\nmargin-bottom: 14px;\ncolor: #0c2340;\ntext-align: center;\n",
      "message_style": "display: flex;\nmargin-bottom: 14px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background-color: #ffffff;\ncolor: #1c2833;\npadding: 10px 14px;\nborder-radius: 10px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #aed6f1;\n",
      "bubble_right_style": "background: linear-gradient(135deg, #1a5276, #2e86c1);\ncolor: #ffffff;\npadding: 10px 14px;\nborder-radius: 10px;\nmax-width: 65%;\nword-wrap: break-word;\nbox-shadow: 0 2px 8px rgba(26, 82, 118, 0.3);\n",
      "avatar_style": "width: 38px;\nheight: 38px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 700;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 10px;\n",
      "avatar_left_style": "background-color: #d6eaf8;\ncolor: #0c2340;\nborder: 1px solid #aed6f1;\n",
      "avatar_right_style": "background: linear-gradient(135deg, #1a5276, #2e86c1);\ncolor: #ffffff;\n"
    },
    "body": {
      "background": "#e8f0f7",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {}
  },
  "sunset": {
    "name": "暮色",
    "description": "日落渐变色系，从金橙到玫瑰紫，温暖有力量",
    "series": "classic",
    "tags": [
      "日落",
      "渐变",
      "温暖"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "#fdf6f0",
      "border_radius": "14px",
      "box_shadow": "0 4px 18px rgba(231, 76, 60, 0.08)"
    },
    "h1": {
      "style": "margin: 1.8em 8px 1em;\npadding: 1em 1.8em;\nfont-size: 22px;\nfont-weight: 800;\nline-height: 1.3;\ncolor: #ffffff;\ntext-align: center;\nbackground: linear-gradient(135deg, #f39c12, #e74c3c, #8e44ad);\nborder-radius: 10px;\nbox-shadow: 0 4px 16px rgba(231, 76, 60, 0.25);\nletter-spacing: 0.06em;\ntext-shadow: 0 1px 3px rgba(0, 0, 0, 0.15);\n"
    },
    "h2": {
      "style": "margin: 2em 8px 0.75em;\npadding: 0px 0px 0.5em 14px;\nborder-left: 4px solid #e74c3c;\nborder-bottom: 1px dashed rgba(231, 76, 60, 0.35);\nfont-size: 20px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #5b2c6f;\n"
    },
    "h3": {
      "style": "margin: 1.8em 8px 0.6em;\npadding: 0px 0px 0.4em 12px;\nborder-left: 4px solid #f39c12;\nfont-size: 18px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #7d3c98;\n"
    },
    "h4": {
      "style": "margin: 1.5em 8px 0.5em;\npadding-left: 12px;\nborder-left: 3px solid #e67e22;\nfont-size: 16px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #8e44ad;\n"
    },
    "h5": {
      "style": "margin: 1.2em 8px 0.4em;\npadding-left: 10px;\nborder-left: 3px solid #f5b041;\nfont-size: 15px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #a04000;\n"
    },
    "h6": {
      "style": "margin: 1em 8px 0.3em;\npadding-left: 8px;\nborder-left: 2px solid #f5cba7;\nfont-size: 14px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #b03a2e;\n"
    },
    "paragraph": {
      "style": "margin: 1.2em 8px;\ncolor: #2d2d2d;\nfont-family: 'PingFang SC', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', sans-serif;\nfont-size: 15px;\nline-height: 1.75;\nletter-spacing: 0.06em;\ntext-align: justify;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 8px;\ncolor: #2d2d2d;\nfont-size: 15px;\n",
      "item_style": "margin: 0.5em 0;\npadding: 0;\nline-height: 1.75;\nfont-size: 15px;\ncolor: #2d2d2d;\n",
      "ul_prefix": "• ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 8px;\npadding: 1.2em;\nbackground-color: #fef9e7;\nborder-top: 3px solid #f39c12;\nborder-radius: 8px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\nfont-size: 14px;\ncolor: #2d2d2d;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "font-size: 90%;\ncolor: #e74c3c;\nbackground-color: rgba(243, 156, 18, 0.1);\npadding: 2px 6px;\nborder-radius: 4px;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 8px;\npadding: 1em 1em 1em 1.5em;\nborder-left: 4px solid #f39c12;\nborder-radius: 6px;\nbackground-color: #fef5e7;\ncolor: #6e2c00;\n",
      "p_inner_style": "margin: 0;\ncolor: #6e2c00;\nline-height: 1.75;\nfont-style: normal;\n"
    },
    "link": {
      "style": "color: #e74c3c;\ntext-decoration: none;\nborder-bottom: 1px solid rgba(231, 76, 60, 0.35);\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 14px;\ncolor: #a04000;\n",
      "img_style": "max-width: 100%;\ndisplay: block;\nmargin: 0.5em auto;\nborder-radius: 8px;\nbox-shadow: 0 3px 12px rgba(231, 76, 60, 0.12);\n"
    },
    "table": {
      "style": "width: 100%;\nborder-collapse: collapse;\nmargin: 1.5em 0;\nfont-size: 14px;\noverflow: hidden;\n",
      "th_style": "padding: 10px 14px;\ntext-align: left;\nfont-weight: 700;\ncolor: #ffffff;\nbackground: linear-gradient(135deg, #e74c3c, #8e44ad);\nborder: 1px solid #c0392b;\n",
      "td_style": "padding: 8px 14px;\nborder: 1px solid #f5cba7;\ncolor: #2d2d2d;\nbackground-color: #ffffff;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 2px;\nmargin: 2em 0;\nbackground: linear-gradient(to right, transparent, #f39c12, #e74c3c, #8e44ad, transparent);\nborder-radius: 2px;\n"
    },
    "bold": {
      "style": "font-weight: 700;\ncolor: #e74c3c;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #8e44ad;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #bfc9ca;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 18px;\nbackground-color: #fef5e7;\nborder-radius: 12px;\nborder: 1px solid #f5cba7;\n",
      "title_style": "font-size: 17px;\nfont-weight: 700;\nmargin-bottom: 14px;\ncolor: #8e44ad;\ntext-align: center;\n",
      "message_style": "display: flex;\nmargin-bottom: 14px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background-color: #ffffff;\ncolor: #2d2d2d;\npadding: 10px 14px;\nborder-radius: 10px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #f5cba7;\n",
      "bubble_right_style": "background: linear-gradient(135deg, #f39c12, #e74c3c);\ncolor: #ffffff;\npadding: 10px 14px;\nborder-radius: 10px;\nmax-width: 65%;\nword-wrap: break-word;\nbox-shadow: 0 2px 8px rgba(231, 76, 60, 0.3);\n",
      "avatar_style": "width: 38px;\nheight: 38px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 700;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 10px;\n",
      "avatar_left_style": "background-color: #fef5e7;\ncolor: #e74c3c;\nborder: 1px solid #f5cba7;\n",
      "avatar_right_style": "background: linear-gradient(135deg, #f39c12, #e74c3c);\ncolor: #ffffff;\n"
    },
    "body": {
      "background": "#fae5d3",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {}
  },
  "tang-poetry": {
    "name": "唐风",
    "description": "唐代诗词古典风格，羊皮纸质感配以深酒红与金色点缀，华贵而不失典雅",
    "series": "oriental",
    "tags": [
      "中国风",
      "诗词",
      "古典"
    ],
    "container": {
      "max_width": "677px",
      "padding": "8px",
      "background": "#f5efe0",
      "border_radius": "12px",
      "box_shadow": "0 2px 12px rgba(80, 50, 20, 0.08)"
    },
    "h1": {
      "style": "padding: 1em 2em;\nmargin: 2em 0 1.2em;\nbackground: linear-gradient(135deg, #f5efe0 0%, #f0e6ce 50%, #f5efe0 100%);\nfont-size: 24px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #800020;\ntext-align: center;\nborder-radius: 6px;\nbox-shadow: 0 2px 8px rgba(128, 0, 32, 0.08);\nborder-top: 2px solid #c49b3c;\nborder-bottom: 2px solid #c49b3c;\nletter-spacing: 0.15em;\n"
    },
    "h2": {
      "style": "margin: 2em 8px 0.75em 0;\npadding: 0.5em 1em 0.5em 16px;\nborder-left: 4px solid #800020;\nfont-size: 20px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #800020;\nbackground: linear-gradient(to right, rgba(196, 155, 60, 0.08), rgba(196, 155, 60, 0.03), transparent);\nborder-bottom: 1px solid rgba(196, 155, 60, 0.3);\n"
    },
    "h3": {
      "style": "margin: 2em 8px 0.75em 0;\npadding: 0.4em 0.8em 0.3em 14px;\nborder-left: 4px solid #c49b3c;\nborder-bottom: 1px dashed rgba(196, 155, 60, 0.3);\nfont-size: 18px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #5a2010;\n"
    },
    "h4": {
      "style": "margin: 1.5em 8px 0.5em 0;\npadding-left: 12px;\nfont-size: 16px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #6a2020;\nborder-left: 3px solid #800020;\n"
    },
    "h5": {
      "style": "margin: 1.2em 8px 0.4em 0;\npadding-left: 10px;\nfont-size: 15px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #7a3020;\nborder-left: 2px solid #c49b3c;\n"
    },
    "h6": {
      "style": "margin: 1em 8px 0.3em 0;\npadding-left: 8px;\nfont-size: 14px;\nfont-weight: bold;\nline-height: 1.3;\ncolor: #8a5040;\nborder-left: 1px solid #c49b3c;\n"
    },
    "paragraph": {
      "style": "margin: 1.2em 8px;\ntext-align: justify;\nline-height: 1.85;\nfont-family: 'PingFang SC', 'STSong', 'Songti SC', 'KaiTi', serif;\nfont-size: 15px;\nletter-spacing: 0.06em;\ncolor: #3a2f20;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 8px;\ncolor: #3a2f20;\nfont-size: 15px;\n",
      "item_style": "margin: 0.5em 0;\npadding: 0;\nline-height: 1.8;\nfont-size: 15px;\ncolor: #3a2f20;\n",
      "ul_prefix": "◦ ",
      "ol_prefix": "{n}、"
    },
    "code_block": {
      "style": "margin: 1.5em 8px;\npadding: 1.2em;\nbackground-color: #f2eadb;\nborder-radius: 4px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\nborder: 1px solid #e0d5c0;\nborder-top: 3px solid #800020;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'Courier New', Menlo, monospace;\nfont-size: 14px;\ncolor: #3a2f20;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "background-color: rgba(196, 155, 60, 0.1);\ncolor: #800020;\nfont-family: 'Courier New', Menlo, monospace;\npadding: 2px 6px;\nborder-radius: 3px;\nfont-size: 90%;\nborder: 1px solid rgba(196, 155, 60, 0.2);\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 0 2em;\npadding: 1em 1.5em;\nborder-left: 4px solid #c49b3c;\nbackground: #f2eadb;\ncolor: #4a3a28;\nborder-radius: 4px;\nbox-shadow: 0 1px 4px rgba(80, 50, 20, 0.06);\n",
      "p_inner_style": "margin: 0;\ncolor: #4a3a28;\nline-height: 1.8;\nfont-style: normal;\nfont-size: 15px;\n"
    },
    "link": {
      "style": "color: #800020;\ntext-decoration: none;\nborder-bottom: 1px dashed rgba(128, 0, 32, 0.4);\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\n",
      "img_style": "max-width: 100%;\nmargin: 1em auto;\ndisplay: block;\nborder-radius: 4px;\nbox-shadow: 0 2px 8px rgba(80, 50, 20, 0.1);\nborder: 1px solid #e0d5c0;\n"
    },
    "table": {
      "style": "margin: 1.5em 0;\nwidth: 100%;\nborder-collapse: collapse;\nfont-size: 15px;\n",
      "th_style": "background: #800020;\ncolor: #ffffff;\npadding: 10px 14px;\ntext-align: left;\nfont-weight: 600;\n",
      "td_style": "border: 1px solid #e0d5c0;\npadding: 10px 14px;\ncolor: #3a2f20;\nbackground: #f8f2e5;\n"
    },
    "hr": {
      "style": ""
    },
    "bold": {
      "style": "font-weight: bold;\ncolor: #800020;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #9a7b30;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #999999;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 20px;\nbackground: linear-gradient(to bottom, #f5efe0, #f0e8d5);\nborder-radius: 8px;\nborder: 1px solid #e0d5c0;\nbox-shadow: 0 2px 8px rgba(80, 50, 20, 0.06);\n",
      "title_style": "font-size: 18px;\nfont-weight: 600;\nmargin-bottom: 16px;\ncolor: #800020;\ntext-align: center;\nletter-spacing: 0.1em;\n",
      "message_style": "display: flex;\nmargin-bottom: 16px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background: #f8f2e5;\ncolor: #4a3a28;\npadding: 12px 16px;\nborder-radius: 12px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #e0d5c0;\n",
      "bubble_right_style": "background: linear-gradient(135deg, #800020, #9a1030);\ncolor: #ffffff;\npadding: 12px 16px;\nborder-radius: 12px;\nmax-width: 65%;\nword-wrap: break-word;\nbox-shadow: 0 2px 6px rgba(128, 0, 32, 0.2);\n",
      "avatar_style": "width: 40px;\nheight: 40px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 600;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 12px;\n",
      "avatar_left_style": "background: #e0d5c0;\ncolor: #800020;\nborder: 2px solid #d0c5a8;\n",
      "avatar_right_style": "background: linear-gradient(135deg, #800020, #9a1030);\ncolor: #ffffff;\n"
    },
    "body": {
      "background": "#ede6d5",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {
      "h2_prefix": "❖ ",
      "hr_text": "— ◆ —",
      "blockquote_prefix": "「",
      "blockquote_suffix": "」"
    }
  },
  "terminal": {
    "name": "终端",
    "description": "复古终端风格，绿色荧光字符，黑客极客感",
    "series": "tech",
    "tags": [
      "终端",
      "黑客",
      "极客"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "#1a1a2e",
      "border_radius": "12px",
      "box_shadow": "0 0 20px rgba(0, 255, 65, 0.08)"
    },
    "h1": {
      "style": "margin: 1.5em 8px 0.75em 0px;\npadding: 0.6em 1em;\nfont-size: 22px;\nfont-weight: 700;\nline-height: 1.2;\ncolor: #00ff41;\ntext-align: left;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\nletter-spacing: 0.05em;\nborder-bottom: 2px solid #00ff41;\n"
    },
    "h2": {
      "style": "margin: 2em 8px 0.75em 0px;\npadding: 0px 0px 0.5em 12px;\nborder-left: 3px solid #00cc33;\nfont-size: 20px;\nfont-weight: 600;\nline-height: 1.2;\ncolor: #00cc33;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n"
    },
    "h3": {
      "style": "margin: 2em 8px 0.75em 0px;\npadding: 0px 0px 0.4em 12px;\nborder-left: 3px solid #00aa22;\nfont-size: 18px;\nfont-weight: 600;\nline-height: 1.2;\ncolor: #00cc33;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n"
    },
    "h4": {
      "style": "margin: 1.5em 8px 0.5em 0px;\npadding-left: 12px;\nborder-left: 3px solid #009918;\nfont-size: 16px;\nfont-weight: 600;\nline-height: 1.2;\ncolor: #00bb2a;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n"
    },
    "h5": {
      "style": "margin: 1.2em 8px 0.4em 0px;\npadding-left: 8px;\nborder-left: 2px solid #009918;\nfont-size: 15px;\nfont-weight: 600;\nline-height: 1.2;\ncolor: #00aa22;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n"
    },
    "h6": {
      "style": "margin: 1em 8px 0.3em 0px;\npadding-left: 6px;\nborder-left: 2px solid #008815;\nfont-size: 14px;\nfont-weight: 600;\nline-height: 1.2;\ncolor: #009918;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n"
    },
    "paragraph": {
      "style": "margin: 1.2em 8px;\ntext-align: left;\nline-height: 1.7;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\nfont-size: 15px;\nletter-spacing: 0.02em;\ncolor: #b0c4b1;\noverflow-wrap: break-word;\n"
    },
    "list": {
      "container_style": "list-style: none;\nmargin: 0em 8px 1.5em;\npadding: 0px;\ntext-align: left;\nline-height: 1.7;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\nfont-size: 15px;\ncolor: #b0c4b1;\n",
      "item_style": "margin: 0.4em 0px;\npadding: 0px;\ntext-align: left;\nline-height: 1.7;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\nfont-size: 15px;\ncolor: #b0c4b1;\n",
      "ul_prefix": "> ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 8px;\npadding: 1.2em;\nbackground-color: #0d0d1a;\nborder-radius: 4px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\nfont-size: 14px;\ncolor: #00ff41;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "background-color: #0d0d1a;\ncolor: #00ff41;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\npadding: 3px 6px;\nborder-radius: 3px;\nfont-size: 90%;\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 0 2em;\npadding: 1em 1em 1em 2em;\nborder-left: 3px solid #006622;\nborder-radius: 4px;\nbackground: #121225;\ncolor: #8aab8b;\nfont-style: normal;\n",
      "p_inner_style": "margin: 0px;\ntext-align: left;\nline-height: 1.7;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\nfont-size: 1em;\ndisplay: block;\ncolor: #8aab8b;\nfont-style: normal;\n"
    },
    "link": {
      "style": "color: #00d4ff;\ntext-decoration: none;\nborder-bottom: 1px solid rgba(0, 212, 255, 0.3);\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\nline-height: 1.7;\nfont-size: 14px;\ncolor: #6a8a6b;\n",
      "img_style": "display: block;\nmax-width: 100%;\nmargin: 0.1em auto 0.5em;\nborder-radius: 4px;\nbox-shadow: 0 0 15px rgba(0, 255, 65, 0.1);\n"
    },
    "table": {
      "style": "margin: 1.5em 0;\nwidth: 100%;\nborder-collapse: collapse;\nfont-size: 14px;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n",
      "th_style": "background: #0d0d1a;\ncolor: #00ff41;\npadding: 10px;\ntext-align: left;\nfont-weight: 600;\nborder: 1px solid #00661a;\n",
      "td_style": "border: 1px solid #1a3a1a;\npadding: 10px;\ncolor: #b0c4b1;\nbackground: #121225;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 1px;\nmargin: 2em 0px;\nborder-top: 1px dashed #00cc33;\nbackground: transparent;\n"
    },
    "bold": {
      "style": "font-weight: bold;\ncolor: #00ff41;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #6a9a6b;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #4a6a4b;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 20px;\nbackground: #121225;\nborder-radius: 8px;\nborder: 1px solid #1a3a1a;\n",
      "title_style": "font-size: 18px;\nfont-weight: 600;\nmargin-bottom: 16px;\ncolor: #00ff41;\ntext-align: center;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n",
      "message_style": "display: flex;\nmargin-bottom: 16px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background: #0d0d1a;\ncolor: #b0c4b1;\npadding: 10px 14px;\nborder-radius: 8px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #1a3a1a;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n",
      "bubble_right_style": "background: #003311;\ncolor: #00ff41;\npadding: 10px 14px;\nborder-radius: 8px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #00661a;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n",
      "avatar_style": "width: 40px;\nheight: 40px;\nborder-radius: 4px;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 600;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 12px;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n",
      "avatar_left_style": "background: #0d0d1a;\ncolor: #00cc33;\nborder: 1px solid #1a3a1a;\n",
      "avatar_right_style": "background: #003311;\ncolor: #00ff41;\nborder: 1px solid #00661a;\n"
    },
    "body": {
      "background": "#0a0a1a",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {
      "h1_prefix": "> _ ",
      "h2_prefix": "$ ",
      "ul_prefix": "> "
    }
  },
  "vogue": {
    "name": "时尚",
    "description": "高端时尚杂志风格，极简黑白搭配优雅衬线字体",
    "series": "magazine",
    "tags": [
      "时尚",
      "高级",
      "杂志"
    ],
    "container": {
      "max_width": "677px",
      "padding": "20px",
      "background": "#ffffff",
      "border_radius": "0px",
      "box_shadow": ""
    },
    "h1": {
      "style": "padding: 0.6em 0;\nmargin: 1.8em 0 1em;\nfont-size: 26px;\nfont-weight: 300;\ntext-align: left;\nletter-spacing: 0.3em;\nline-height: 1.4;\ncolor: #000000;\nborder-bottom: 2px solid #000000;\nfont-family: Georgia, 'Times New Roman', serif;\n"
    },
    "h2": {
      "style": "margin: 2em 0 0.8em;\npadding: 0 0 0.5em 0;\nfont-size: 20px;\nfont-weight: 400;\nletter-spacing: 0.15em;\nline-height: 1.3;\ncolor: #000000;\nborder-bottom: 1px solid #dddddd;\nfont-family: Georgia, 'Times New Roman', serif;\n"
    },
    "h3": {
      "style": "margin: 1.8em 0 0.6em;\npadding: 0;\nfont-size: 18px;\nfont-weight: 400;\nletter-spacing: 0.1em;\nline-height: 1.3;\ncolor: #000000;\nfont-family: Georgia, 'Times New Roman', serif;\n"
    },
    "h4": {
      "style": "margin: 1.5em 0 0.5em;\npadding: 0;\nfont-size: 16px;\nfont-weight: 600;\nletter-spacing: 0.08em;\nline-height: 1.3;\ncolor: #333333;\nfont-family: Georgia, 'Times New Roman', serif;\n"
    },
    "h5": {
      "style": "margin: 1.2em 0 0.4em;\npadding: 0;\nfont-size: 15px;\nfont-weight: 600;\nletter-spacing: 0.05em;\nline-height: 1.3;\ncolor: #333333;\nfont-family: Georgia, 'Times New Roman', serif;\n"
    },
    "h6": {
      "style": "margin: 1em 0 0.3em;\npadding: 0;\nfont-size: 14px;\nfont-weight: 600;\nletter-spacing: 0.05em;\nline-height: 1.3;\ncolor: #666666;\nfont-family: Georgia, 'Times New Roman', serif;\n"
    },
    "paragraph": {
      "style": "margin: 1.4em 0;\ncolor: #333333;\nfont-family: Georgia, 'Times New Roman', serif;\nfont-size: 16px;\nline-height: 1.9;\nletter-spacing: 0.02em;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 0;\ncolor: #333333;\nfont-family: Georgia, 'Times New Roman', serif;\nfont-size: 16px;\n",
      "item_style": "margin: 0.5em 0;\npadding: 0;\nline-height: 1.8;\nfont-size: 16px;\n",
      "ul_prefix": "— ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 0;\npadding: 1.2em;\nbackground-color: #f5f5f5;\nborder-radius: 0px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\nborder: 1px solid #e0e0e0;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\nfont-size: 14px;\ncolor: #333333;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "font-size: 90%;\ncolor: #333333;\nbackground-color: #f0f0f0;\npadding: 2px 6px;\nborder-radius: 2px;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\n"
    },
    "blockquote": {
      "style": "margin: 2em 0;\npadding: 1.5em 2em;\nborder-left: none;\nborder-top: 1px solid #cccccc;\nborder-bottom: 1px solid #cccccc;\ntext-align: center;\n",
      "p_inner_style": "margin: 0;\ncolor: #666666;\nfont-size: 20px;\nline-height: 1.7;\nfont-style: italic;\nfont-family: Georgia, 'Times New Roman', serif;\nletter-spacing: 0.02em;\n"
    },
    "link": {
      "style": "color: #000000;\ntext-decoration: underline;\n"
    },
    "image": {
      "container_style": "margin: 2em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 13px;\ncolor: #999999;\nfont-family: Georgia, 'Times New Roman', serif;\nfont-style: italic;\n",
      "img_style": "max-width: 100%;\ndisplay: block;\nmargin: 1.5em auto;\nborder-radius: 0px;\nbox-shadow: 0 2px 12px rgba(0, 0, 0, 0.08);\n"
    },
    "table": {
      "style": "width: 100%;\nborder-collapse: collapse;\nmargin: 1.5em 0;\nfont-family: Georgia, 'Times New Roman', serif;\nfont-size: 15px;\n",
      "th_style": "padding: 12px 15px;\ntext-align: left;\nfont-weight: 600;\ncolor: #000000;\nborder-bottom: 2px solid #000000;\nletter-spacing: 0.08em;\n",
      "td_style": "padding: 10px 15px;\nborder-bottom: 1px solid #e0e0e0;\ncolor: #333333;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 1px;\nmargin: 2.5em 0;\nbackground-color: #000000;\n"
    },
    "bold": {
      "style": "font-weight: 700;\ncolor: #000000;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #333333;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #999999;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 20px;\nbackground-color: #fafafa;\nborder-radius: 0px;\nborder: 1px solid #e0e0e0;\n",
      "title_style": "font-size: 18px;\nfont-weight: 300;\nmargin-bottom: 16px;\ncolor: #000000;\ntext-align: center;\nletter-spacing: 0.15em;\nfont-family: Georgia, 'Times New Roman', serif;\n",
      "message_style": "display: flex;\nmargin-bottom: 16px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background-color: #ffffff;\ncolor: #333333;\npadding: 10px 14px;\nborder-radius: 4px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #e0e0e0;\nfont-family: Georgia, 'Times New Roman', serif;\n",
      "bubble_right_style": "background-color: #000000;\ncolor: #ffffff;\npadding: 10px 14px;\nborder-radius: 4px;\nmax-width: 65%;\nword-wrap: break-word;\n",
      "avatar_style": "width: 40px;\nheight: 40px;\nborder-radius: 0px;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 300;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 12px;\nletter-spacing: 0.05em;\n",
      "avatar_left_style": "background-color: #f0f0f0;\ncolor: #000000;\nborder: 1px solid #e0e0e0;\n",
      "avatar_right_style": "background-color: #000000;\ncolor: #ffffff;\n"
    },
    "decorations": {
      "h2_prefix": "",
      "blockquote_prefix": "",
      "blockquote_suffix": "",
      "hr_text": ""
    },
    "body": {
      "background": "#f5f5f0",
      "padding": "16px",
      "margin": "0"
    }
  },
  "vscode": {
    "name": "VS Code",
    "description": "Visual Studio Code 编辑器风格，经典 IDE 暗色主题",
    "series": "tech",
    "tags": [
      "IDE",
      "开发者",
      "编程"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "#1e1e1e",
      "border_radius": "12px",
      "box_shadow": "0 2px 12px rgba(0, 0, 0, 0.4)"
    },
    "h1": {
      "style": "margin: 1.5em 8px 0.75em 0px;\npadding: 0.4em 0;\nfont-size: 22px;\nfont-weight: 700;\nline-height: 1.25;\ncolor: #569cd6;\nborder-bottom: 2px solid #333333;\nfont-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;\n"
    },
    "h2": {
      "style": "margin: 2em 8px 0.75em 0px;\npadding: 0px 0px 0.35em 0px;\nfont-size: 20px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #4ec9b0;\nborder-bottom: 1px solid #333333;\nfont-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;\n"
    },
    "h3": {
      "style": "margin: 2em 8px 0.75em 0px;\npadding: 0px;\nfont-size: 18px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #dcdcaa;\nfont-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;\n"
    },
    "h4": {
      "style": "margin: 1.5em 8px 0.5em 0px;\npadding: 0px;\nfont-size: 16px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #9cdcfe;\nfont-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;\n"
    },
    "h5": {
      "style": "margin: 1.2em 8px 0.4em 0px;\npadding: 0px;\nfont-size: 15px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #c586c0;\nfont-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;\n"
    },
    "h6": {
      "style": "margin: 1em 8px 0.3em 0px;\npadding: 0px;\nfont-size: 14px;\nfont-weight: 600;\nline-height: 1.25;\ncolor: #808080;\nfont-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, sans-serif;\n"
    },
    "paragraph": {
      "style": "margin: 1em 8px;\ntext-align: left;\nline-height: 1.6;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\nfont-size: 15px;\ncolor: #d4d4d4;\noverflow-wrap: break-word;\n"
    },
    "list": {
      "container_style": "list-style: none;\nmargin: 0em 8px 1em;\npadding: 0px;\ntext-align: left;\nline-height: 1.6;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\nfont-size: 15px;\ncolor: #d4d4d4;\n",
      "item_style": "margin: 0.3em 0px;\npadding: 0px;\ntext-align: left;\nline-height: 1.6;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\nfont-size: 15px;\ncolor: #d4d4d4;\n",
      "ul_prefix": "• ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 8px;\npadding: 16px;\nbackground-color: #1e1e1e;\nborder-radius: 4px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\nborder: 1px solid #333333;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'Cascadia Code', 'Fira Code', Menlo, Monaco, Consolas, monospace;\nfont-size: 14px;\ncolor: #d4d4d4;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "background-color: #2d2d2d;\ncolor: #ce9178;\nfont-family: 'Cascadia Code', 'Fira Code', Menlo, Monaco, Consolas, monospace;\npadding: 3px 6px;\nborder-radius: 3px;\nfont-size: 90%;\n"
    },
    "blockquote": {
      "style": "margin: 1em 0;\npadding: 0.8em 1em 0.8em 1.5em;\nborder-left: 4px solid #007acc;\nborder-radius: 0px;\nbackground: #252526;\ncolor: #d4d4d4;\nfont-style: normal;\n",
      "p_inner_style": "margin: 0px;\ntext-align: left;\nline-height: 1.6;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\nfont-size: 15px;\ndisplay: block;\ncolor: #d4d4d4;\nfont-style: normal;\n"
    },
    "link": {
      "style": "color: #569cd6;\ntext-decoration: none;\nborder-bottom: 1px solid rgba(86, 156, 214, 0.3);\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 14px;\ncolor: #808080;\n",
      "img_style": "display: block;\nmax-width: 100%;\nmargin: 0.1em auto 0.5em;\nborder-radius: 4px;\nbox-shadow: 0 2px 8px rgba(0, 0, 0, 0.4);\nborder: 1px solid #333333;\n"
    },
    "table": {
      "style": "margin: 1.5em 0;\nwidth: 100%;\nborder-collapse: collapse;\nfont-size: 14px;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\ncolor: #d4d4d4;\n",
      "th_style": "background: #252526;\ncolor: #569cd6;\npadding: 10px 13px;\ntext-align: left;\nfont-weight: 600;\nborder: 1px solid #333333;\n",
      "td_style": "border: 1px solid #333333;\npadding: 10px 13px;\ncolor: #d4d4d4;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 1px;\nmargin: 2em 0;\nbackground: #333333;\n"
    },
    "bold": {
      "style": "font-weight: 600;\ncolor: #569cd6;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #c586c0;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #808080;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 20px;\nbackground: #252526;\nborder-radius: 8px;\nborder: 1px solid #333333;\n",
      "title_style": "font-size: 18px;\nfont-weight: 600;\nmargin-bottom: 16px;\ncolor: #569cd6;\ntext-align: center;\n",
      "message_style": "display: flex;\nmargin-bottom: 16px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background: #2d2d2d;\ncolor: #d4d4d4;\npadding: 10px 14px;\nborder-radius: 8px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #333333;\nfont-family: Menlo, Monaco, Consolas, 'Courier New', monospace;\n",
      "bubble_right_style": "background: #007acc;\ncolor: #ffffff;\npadding: 10px 14px;\nborder-radius: 8px;\nmax-width: 65%;\nword-wrap: break-word;\n",
      "avatar_style": "width: 40px;\nheight: 40px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 600;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 12px;\n",
      "avatar_left_style": "background: #2d2d2d;\ncolor: #d4d4d4;\nborder: 1px solid #333333;\n",
      "avatar_right_style": "background: #007acc;\ncolor: #ffffff;\n"
    },
    "body": {
      "background": "#1e1e1e",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {}
  },
  "xiaohongshu": {
    "name": "小红书",
    "description": "小红书种草风格，粉红色系，活泼年轻有趣",
    "series": "social",
    "tags": [
      "小红书",
      "种草",
      "年轻"
    ],
    "container": {
      "max_width": "677px",
      "padding": "16px",
      "background": "#ffffff",
      "border_radius": "16px",
      "box_shadow": "0 4px 20px rgba(255, 36, 66, 0.08)"
    },
    "h1": {
      "style": "padding: 0.8em 1.5em;\nmargin: 1.4em 0 1em;\nfont-size: 22px;\nfont-weight: 700;\ntext-align: center;\nletter-spacing: 0.05em;\nline-height: 1.3;\nbackground: linear-gradient(135deg, #ff2442 0%, #ff6b81 100%);\ncolor: #ffffff;\nborder-radius: 20px;\nbox-shadow: 0 4px 16px rgba(255, 36, 66, 0.25);\n"
    },
    "h2": {
      "style": "margin: 2em 0 0.8em;\npadding: 0;\nfont-size: 20px;\nfont-weight: 700;\nline-height: 1.3;\ncolor: #ff2442;\n"
    },
    "h3": {
      "style": "margin: 1.8em 0 0.6em;\npadding: 0;\nfont-size: 18px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #ff2442;\n"
    },
    "h4": {
      "style": "margin: 1.5em 0 0.5em;\npadding: 0;\nfont-size: 16px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #ff4d6a;\n"
    },
    "h5": {
      "style": "margin: 1.2em 0 0.4em;\npadding: 0;\nfont-size: 15px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #ff4d6a;\n"
    },
    "h6": {
      "style": "margin: 1em 0 0.3em;\npadding: 0;\nfont-size: 14px;\nfont-weight: 600;\nline-height: 1.3;\ncolor: #ff6b81;\n"
    },
    "paragraph": {
      "style": "margin: 1.2em 0;\ncolor: #333333;\nfont-size: 15px;\nline-height: 2.0;\nletter-spacing: 0.05em;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.2em 0;\ncolor: #333333;\nfont-size: 15px;\n",
      "item_style": "margin: 0.5em 0;\npadding: 0;\nline-height: 1.9;\nfont-size: 15px;\nletter-spacing: 0.05em;\n",
      "ul_prefix": "💕 ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.5em 0;\npadding: 1.2em;\nbackground-color: #fff5f7;\nborder-radius: 12px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.5;\nborder: 1px solid #ffe0e6;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\nfont-size: 14px;\ncolor: #333333;\nline-height: 1.5;\n"
    },
    "inline_code": {
      "style": "font-size: 90%;\ncolor: #ff2442;\nbackground-color: #fff0f3;\npadding: 2px 6px;\nborder-radius: 6px;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\n"
    },
    "blockquote": {
      "style": "margin: 1.5em 0;\npadding: 1em 1.2em;\nborder-left: 4px solid #ff2442;\nbackground-color: #fff0f3;\nborder-radius: 12px;\n",
      "p_inner_style": "margin: 0;\ncolor: #555555;\nline-height: 1.9;\nfont-style: normal;\nletter-spacing: 0.05em;\n"
    },
    "link": {
      "style": "color: #ff2442;\ntext-decoration: none;\nborder-bottom: 1px solid rgba(255, 36, 66, 0.3);\n"
    },
    "image": {
      "container_style": "margin: 1.5em 0;\ntext-align: center;\nline-height: 1.6;\nfont-size: 14px;\ncolor: #ff6b81;\n",
      "img_style": "max-width: 100%;\ndisplay: block;\nmargin: 1.5em auto;\nborder-radius: 16px;\nbox-shadow: 0 4px 16px rgba(255, 36, 66, 0.12);\n"
    },
    "table": {
      "style": "width: 100%;\nborder-collapse: collapse;\nmargin: 1.5em 0;\nfont-size: 15px;\nborder-radius: 12px;\noverflow: hidden;\n",
      "th_style": "padding: 12px 15px;\ntext-align: left;\nfont-weight: 600;\ncolor: #ffffff;\nbackground: linear-gradient(135deg, #ff2442, #ff6b81);\n",
      "td_style": "padding: 10px 15px;\nborder-bottom: 1px solid #ffe0e6;\ncolor: #333333;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 2px;\nmargin: 2em 0;\nbackground: linear-gradient(to right, transparent, #ff2442, #ff6b81, transparent);\n"
    },
    "bold": {
      "style": "font-weight: 700;\ncolor: #ff2442;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #ff6b81;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #cccccc;\n"
    },
    "dialogue": {
      "container_style": "margin: 2em 0;\npadding: 20px;\nbackground-color: #fff5f7;\nborder-radius: 20px;\nborder: 1px solid #ffe0e6;\n",
      "title_style": "font-size: 18px;\nfont-weight: 700;\nmargin-bottom: 16px;\ncolor: #ff2442;\ntext-align: center;\n",
      "message_style": "display: flex;\nmargin-bottom: 16px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background-color: #ffffff;\ncolor: #333333;\npadding: 10px 14px;\nborder-radius: 16px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #ffe0e6;\n",
      "bubble_right_style": "background: linear-gradient(135deg, #ff2442, #ff6b81);\ncolor: #ffffff;\npadding: 10px 14px;\nborder-radius: 16px;\nmax-width: 65%;\nword-wrap: break-word;\nbox-shadow: 0 2px 8px rgba(255, 36, 66, 0.2);\n",
      "avatar_style": "width: 40px;\nheight: 40px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 600;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 12px;\n",
      "avatar_left_style": "background-color: #fff0f3;\ncolor: #ff2442;\nborder: 1px solid #ffe0e6;\n",
      "avatar_right_style": "background: linear-gradient(135deg, #ff2442, #ff6b81);\ncolor: #ffffff;\nbox-shadow: 0 2px 8px rgba(255, 36, 66, 0.3);\n"
    },
    "decorations": {
      "h2_prefix": "✨ ",
      "blockquote_prefix": "",
      "blockquote_suffix": "",
      "hr_text": ""
    },
    "body": {
      "background": "#fff5f5",
      "padding": "16px",
      "margin": "0"
    }
  },
  "zen-garden": {
    "name": "枯山水",
    "description": "日式禅意极简风格，极度克制的留白与纤细线条，传达枯山水庭院的宁静空寂",
    "series": "oriental",
    "tags": [
      "日式",
      "极简",
      "禅意"
    ],
    "container": {
      "max_width": "677px",
      "padding": "8px",
      "background": "#fafaf8",
      "border_radius": "12px",
      "box_shadow": ""
    },
    "h1": {
      "style": "padding: 1.2em 1em 0.8em;\nmargin: 2.5em 0 1.5em;\nfont-size: 24px;\nfont-weight: 300;\nline-height: 1.4;\ncolor: #1a1a1a;\ntext-align: center;\nletter-spacing: 0.3em;\nborder-bottom: 1px solid #d0d0d0;\n"
    },
    "h2": {
      "style": "margin: 2.5em 8px 1em 0;\npadding: 0.3em 0 0.3em 14px;\nborder-left: 2px solid #333333;\nfont-size: 19px;\nfont-weight: 400;\nline-height: 1.4;\ncolor: #2a2a2a;\nletter-spacing: 0.12em;\n"
    },
    "h3": {
      "style": "margin: 2em 8px 0.8em 0;\npadding: 0.2em 0 0.2em 12px;\nborder-left: 1px solid #666666;\nfont-size: 17px;\nfont-weight: 400;\nline-height: 1.4;\ncolor: #333333;\nletter-spacing: 0.08em;\n"
    },
    "h4": {
      "style": "margin: 1.8em 8px 0.6em 0;\npadding-left: 10px;\nfont-size: 16px;\nfont-weight: 500;\nline-height: 1.4;\ncolor: #3a3a3a;\nborder-left: 1px solid #999999;\n"
    },
    "h5": {
      "style": "margin: 1.5em 8px 0.5em 0;\npadding-left: 8px;\nfont-size: 15px;\nfont-weight: 500;\nline-height: 1.4;\ncolor: #444444;\n"
    },
    "h6": {
      "style": "margin: 1.2em 8px 0.4em 0;\npadding-left: 6px;\nfont-size: 14px;\nfont-weight: 500;\nline-height: 1.4;\ncolor: #555555;\n"
    },
    "paragraph": {
      "style": "margin: 1.5em 8px;\ntext-align: justify;\nline-height: 1.9;\nfont-family: 'PingFang SC', -apple-system-font, 'Hiragino Sans', 'Noto Sans CJK SC', sans-serif;\nfont-size: 15px;\nletter-spacing: 0.06em;\ncolor: #444444;\n"
    },
    "list": {
      "container_style": "list-style: none;\npadding: 0;\nmargin: 1.5em 8px;\ncolor: #444444;\nfont-size: 15px;\n",
      "item_style": "margin: 0.6em 0;\npadding: 0;\nline-height: 1.85;\nfont-size: 15px;\ncolor: #444444;\n",
      "ul_prefix": "– ",
      "ol_prefix": "{n}. "
    },
    "code_block": {
      "style": "margin: 1.8em 8px;\npadding: 1.4em;\nbackground-color: #f5f5f3;\nborder-radius: 4px;\noverflow-x: auto;\nfont-size: 14px;\nline-height: 1.6;\nborder: 1px solid #e8e8e6;\n",
      "code_inner_style": "background: none;\npadding: 0;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\nfont-size: 14px;\ncolor: #3a3a3a;\nline-height: 1.6;\n"
    },
    "inline_code": {
      "style": "background-color: #f0f0ee;\ncolor: #333333;\nfont-family: 'SFMono-Regular', Consolas, Menlo, monospace;\npadding: 2px 6px;\nborder-radius: 3px;\nfont-size: 90%;\n"
    },
    "blockquote": {
      "style": "margin: 2em 0;\npadding: 0.8em 1.5em;\nborder-left: 1px solid #cccccc;\ncolor: #666666;\nfont-style: italic;\n",
      "p_inner_style": "margin: 0;\ncolor: #666666;\nline-height: 1.85;\nfont-style: italic;\nfont-size: 15px;\n"
    },
    "link": {
      "style": "color: #333333;\ntext-decoration: none;\nborder-bottom: 1px solid #cccccc;\n"
    },
    "image": {
      "container_style": "margin: 2em 0;\ntext-align: center;\n",
      "img_style": "max-width: 100%;\nmargin: 1em auto;\ndisplay: block;\nborder-radius: 2px;\n"
    },
    "table": {
      "style": "margin: 1.8em 0;\nwidth: 100%;\nborder-collapse: collapse;\nfont-size: 15px;\n",
      "th_style": "background: #f0f0ee;\ncolor: #2a2a2a;\npadding: 10px 14px;\ntext-align: left;\nfont-weight: 500;\nborder-bottom: 1px solid #cccccc;\n",
      "td_style": "border-bottom: 1px solid #e8e8e6;\npadding: 10px 14px;\ncolor: #444444;\n"
    },
    "hr": {
      "style": "border: none;\nheight: 1px;\nmargin: 3em 0;\nbackground: #d8d8d6;\n"
    },
    "bold": {
      "style": "font-weight: 600;\n"
    },
    "italic": {
      "style": "font-style: italic;\ncolor: #888888;\n"
    },
    "strikethrough": {
      "style": "text-decoration: line-through;\ncolor: #aaaaaa;\n"
    },
    "dialogue": {
      "container_style": "margin: 2.5em 0;\npadding: 20px;\nbackground: #fafaf8;\nborder-radius: 8px;\nborder: 1px solid #e8e8e6;\n",
      "title_style": "font-size: 17px;\nfont-weight: 400;\nmargin-bottom: 18px;\ncolor: #2a2a2a;\ntext-align: center;\nletter-spacing: 0.15em;\n",
      "message_style": "display: flex;\nmargin-bottom: 16px;\nalign-items: flex-start;\n",
      "bubble_left_style": "background: #f5f5f3;\ncolor: #444444;\npadding: 12px 16px;\nborder-radius: 12px;\nmax-width: 65%;\nword-wrap: break-word;\nborder: 1px solid #e8e8e6;\n",
      "bubble_right_style": "background: #333333;\ncolor: #ffffff;\npadding: 12px 16px;\nborder-radius: 12px;\nmax-width: 65%;\nword-wrap: break-word;\n",
      "avatar_style": "width: 40px;\nheight: 40px;\nborder-radius: 50%;\ndisplay: flex;\nalign-items: center;\njustify-content: center;\nfont-weight: 400;\nfont-size: 14px;\nflex-shrink: 0;\nmargin: 0 12px;\n",
      "avatar_left_style": "background: #e8e8e6;\ncolor: #555555;\n",
      "avatar_right_style": "background: #333333;\ncolor: #ffffff;\n"
    },
    "body": {
      "background": "#f2f2f0",
      "padding": "16px",
      "margin": "0"
    },
    "decorations": {
      "h2_prefix": "· ",
      "ul_prefix": "– "
    }
  }
};
