#!/usr/bin/env python3
"""
Build script: compile YAML themes to showcase/js/themes.js
Run: python scripts/build_themes.py
"""

import yaml
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
THEMES_DIR = ROOT / "themes"
OUTPUT = ROOT / "showcase" / "js" / "themes.js"


def main():
    themes = {}
    count = 0

    for f in sorted(THEMES_DIR.glob("*.yaml")):
        if f.stem.startswith("_"):
            continue
        try:
            with open(f, "r", encoding="utf-8") as fp:
                data = yaml.safe_load(fp)
                themes[f.stem] = data
                count += 1
        except Exception as e:
            print(f"Warning: failed to load {f.name}: {e}", file=sys.stderr)

    # Write JS module
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    themes_json = json.dumps(themes, ensure_ascii=False, indent=2)

    with open(OUTPUT, "w", encoding="utf-8") as fp:
        fp.write(f"// Auto-generated by build_themes.py — do not edit\n")
        fp.write(f"// {count} themes compiled\n")
        fp.write(f"const THEMES = {themes_json};\n")

    print(f"Built {count} themes -> {OUTPUT}")


if __name__ == "__main__":
    main()
